import { chromium } from 'playwright';
const BASE='http://127.0.0.1:5173';
const b=await chromium.launch({args:['--no-sandbox','--disable-setuid-sandbox','--disable-dev-shm-usage']});
const adm=await b.newContext({viewport:{width:1366,height:900}}); const ap=await adm.newPage(); ap.setDefaultTimeout(8000);
await ap.goto(BASE+'/login',{waitUntil:'domcontentloaded'}); await ap.waitForTimeout(600);
await ap.fill('input[type=email]','ayushborwal004@gmail.com'); await ap.fill('input[type=password]','TestPass123!'); await ap.click('button[type=submit]'); await ap.waitForTimeout(3000);
await ap.goto(BASE+'/employees',{waitUntil:'domcontentloaded'}); await ap.waitForTimeout(6000);
const main=await ap.evaluate(()=>{ const m=document.querySelector('main')||document.body; return Array.from(m.querySelectorAll('button, a')).map(x=>(x.innerText||'').replace(/\s+/g,' ').trim()).filter(t=>t).slice(0,40); });
console.log('MAIN CONTENT BTNS => '+JSON.stringify(main));
await b.close();
