<?php

return [
    'classifier_version' => '2026-05-04.1',
    'fallback_classification' => [
        'unknown' => 'neutral',
        'browser_without_context' => 'context_dependent',
    ],
    'browser_apps' => [
        'google chrome',
        'chrome',
        'microsoft edge',
        'edge',
        'mozilla firefox',
        'firefox',
        'brave',
        'opera',
        'safari',
        'vivaldi',
    ],
    'browser_title_patterns' => [
        '/\s*-\s*google chrome$/iu',
        '/\s*-\s*chrome$/iu',
        '/\s*-\s*microsoft edge$/iu',
        '/\s*-\s*mozilla firefox$/iu',
        '/\s*-\s*firefox$/iu',
        '/\s*-\s*brave$/iu',
        '/\s*-\s*opera$/iu',
        '/\s*-\s*safari$/iu',
        '/\s*-\s*vivaldi$/iu',
    ],
    'app_aliases' => [
        'codex' => ['codex'],
        'vscode' => ['visual studio code', 'vs code', 'code.exe', 'vscode', 'code'],
        'terminal' => ['terminal', 'windows terminal', 'powershell', 'cmd', 'command prompt', 'git bash'],
        'figma' => ['figma'],
        'postman' => ['postman'],
        'dbeaver' => ['dbeaver'],
        'mysql workbench' => ['mysql workbench'],
        'slack' => ['slack'],
        'teams' => ['microsoft teams', 'teams'],
        'zoom' => ['zoom'],
        'notion' => ['notion'],
        'whatsapp' => ['whatsapp'],
        'telegram' => ['telegram'],
        'discord' => ['discord'],
        'chatgpt' => ['chatgpt'],
        'claude' => ['claude'],
        'gemini' => ['gemini'],
    ],
    'default_rules' => [
        ['name' => 'GitHub', 'target_type' => 'domain', 'match_mode' => 'exact', 'target_value' => 'github.com', 'classification' => 'productive', 'priority' => 300, 'reason' => 'Code hosting and review'],
        ['name' => 'GitLab', 'target_type' => 'domain', 'match_mode' => 'exact', 'target_value' => 'gitlab.com', 'classification' => 'productive', 'priority' => 300, 'reason' => 'Code hosting and review'],
        ['name' => 'Bitbucket', 'target_type' => 'domain', 'match_mode' => 'exact', 'target_value' => 'bitbucket.org', 'classification' => 'productive', 'priority' => 300, 'reason' => 'Code hosting and review'],
        ['name' => 'Jira', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'jira', 'classification' => 'productive', 'priority' => 280, 'reason' => 'Task and issue tracking'],
        ['name' => 'Confluence', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'confluence', 'classification' => 'productive', 'priority' => 280, 'reason' => 'Documentation workspace'],
        ['name' => 'Notion', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'notion', 'classification' => 'productive', 'priority' => 280, 'reason' => 'Documentation workspace'],
        ['name' => 'Slack', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'slack', 'classification' => 'productive', 'priority' => 260, 'reason' => 'Work communication'],
        ['name' => 'Teams', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'teams', 'classification' => 'productive', 'priority' => 260, 'reason' => 'Work communication'],
        ['name' => 'Zoom', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'zoom', 'classification' => 'productive', 'priority' => 260, 'reason' => 'Meetings and calls'],
        ['name' => 'VS Code', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'vscode', 'classification' => 'productive', 'priority' => 320, 'reason' => 'Software development environment'],
        ['name' => 'Terminal', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'terminal', 'classification' => 'productive', 'priority' => 320, 'reason' => 'Engineering and operations tooling'],
        ['name' => 'Postman', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'postman', 'classification' => 'productive', 'priority' => 260, 'reason' => 'API testing'],
        ['name' => 'Figma', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'figma', 'classification' => 'productive', 'priority' => 260, 'reason' => 'Design tooling'],
        ['name' => 'Google Docs', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'docs.google', 'classification' => 'productive', 'priority' => 250, 'reason' => 'Document editing'],
        ['name' => 'Google Sheets', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'sheets.google', 'classification' => 'productive', 'priority' => 250, 'reason' => 'Spreadsheet work'],
        ['name' => 'Google Drive', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'drive.google', 'classification' => 'productive', 'priority' => 250, 'reason' => 'File collaboration'],
        ['name' => 'Stack Overflow', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'stackoverflow.com', 'classification' => 'productive', 'priority' => 240, 'reason' => 'Technical research'],
        ['name' => 'MDN', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'developer.mozilla.org', 'classification' => 'productive', 'priority' => 240, 'reason' => 'Technical documentation'],
        ['name' => 'Microsoft Learn', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'learn.microsoft.com', 'classification' => 'productive', 'priority' => 240, 'reason' => 'Technical documentation'],
        ['name' => 'Trello', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'trello.com', 'classification' => 'productive', 'priority' => 220, 'reason' => 'Task management'],
        ['name' => 'Asana', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'asana.com', 'classification' => 'productive', 'priority' => 220, 'reason' => 'Task management'],
        ['name' => 'Linear', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'linear.app', 'classification' => 'productive', 'priority' => 220, 'reason' => 'Task management'],
        ['name' => 'ClickUp', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'clickup.com', 'classification' => 'productive', 'priority' => 220, 'reason' => 'Task management'],
        ['name' => 'Outlook', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'outlook', 'classification' => 'productive', 'priority' => 200, 'reason' => 'Work email'],
        ['name' => 'Gmail', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'mail.google', 'classification' => 'productive', 'priority' => 200, 'reason' => 'Work email'],
        ['name' => 'Google Calendar', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'calendar.google', 'classification' => 'productive', 'priority' => 200, 'reason' => 'Calendar and scheduling'],
        ['name' => 'LinkedIn', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'linkedin.com', 'classification' => 'productive', 'priority' => 220, 'reason' => 'Professional networking and recruiting'],
        ['name' => 'ChatGPT', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'chatgpt', 'classification' => 'productive', 'priority' => 210, 'reason' => 'Work assistant tooling'],
        ['name' => 'Claude', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'claude', 'classification' => 'productive', 'priority' => 210, 'reason' => 'Work assistant tooling'],
        ['name' => 'Gemini', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'gemini', 'classification' => 'productive', 'priority' => 210, 'reason' => 'Work assistant tooling'],
        ['name' => 'Codex', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'codex', 'classification' => 'productive', 'priority' => 210, 'reason' => 'Engineering assistant tooling'],
        ['name' => 'YouTube', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'youtube.com', 'classification' => 'context_dependent', 'priority' => 210, 'reason' => 'Video can be training or entertainment depending on context'],
        ['name' => 'WhatsApp Web', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'web.whatsapp.com', 'classification' => 'unproductive', 'priority' => 215, 'reason' => 'Web chat usage is treated as non-work browsing in monitoring summaries'],
        ['name' => 'WhatsApp', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'whatsapp', 'classification' => 'context_dependent', 'priority' => 210, 'reason' => 'Messaging can be work or personal'],
        ['name' => 'Telegram', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'telegram', 'classification' => 'context_dependent', 'priority' => 210, 'reason' => 'Messaging can be work or personal'],
        ['name' => 'Discord', 'target_type' => 'app', 'match_mode' => 'contains', 'target_value' => 'discord', 'classification' => 'context_dependent', 'priority' => 180, 'reason' => 'Chat server may or may not be work-related'],
        ['name' => 'Netflix', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'netflix.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Entertainment streaming'],
        ['name' => 'Instagram', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'instagram.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Social media entertainment'],
        ['name' => 'Facebook', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'facebook.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Social media entertainment'],
        ['name' => 'Twitter X', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'x.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Social media entertainment'],
        ['name' => 'Twitter', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'twitter.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Social media entertainment'],
        ['name' => 'Reddit', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'reddit.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Community browsing and entertainment'],
        ['name' => 'TikTok', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'tiktok.com', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Entertainment browsing'],
        ['name' => 'Twitch', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'twitch.tv', 'classification' => 'unproductive', 'priority' => 300, 'reason' => 'Entertainment streaming'],
        ['name' => 'Pinterest', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'pinterest.com', 'classification' => 'unproductive', 'priority' => 280, 'reason' => 'General browsing and inspiration'],
        ['name' => 'Spotify', 'target_type' => 'domain', 'match_mode' => 'contains', 'target_value' => 'spotify.com', 'classification' => 'unproductive', 'priority' => 250, 'reason' => 'Music streaming'],
    ],
    'keyword_fallback_rules' => [
        ['label' => 'Browser Extensions', 'tool_type' => 'website', 'classification' => 'productive', 'keywords' => ['chrome://extensions', 'edge://extensions', 'brave://extensions', 'extensions'], 'reason' => 'Browser extension setup and administration', 'priority' => 240],
        ['label' => 'Browser Settings', 'tool_type' => 'website', 'classification' => 'neutral', 'keywords' => ['chrome://settings', 'edge://settings', 'brave://settings', 'settings - privacy and security', 'settings - you and google'], 'reason' => 'Browser settings and preferences', 'priority' => 210],
        ['label' => 'File Explorer', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['this pc', 'file explorer', 'windows explorer', 'downloads', 'documents'], 'reason' => 'Local file and workspace management', 'priority' => 220],
        ['label' => 'MongoDB', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['mongodb', 'mongodb compass'], 'reason' => 'Database tooling', 'priority' => 220],
        ['label' => 'PostgreSQL', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['postgresql', 'postgres', 'pgadmin'], 'reason' => 'Database tooling', 'priority' => 220],
        ['label' => 'MySQL', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['mysql', 'mysql workbench'], 'reason' => 'Database tooling', 'priority' => 220],
        ['label' => 'Redis', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['redis'], 'reason' => 'Data store tooling', 'priority' => 220],
        ['label' => 'Oracle', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['oracle'], 'reason' => 'Database tooling', 'priority' => 220],
        ['label' => 'Jupyter', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['jupyter'], 'reason' => 'Notebook and analysis tooling', 'priority' => 220],
        ['label' => 'Anaconda', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['anaconda'], 'reason' => 'Data science environment', 'priority' => 220],
        ['label' => 'TensorFlow', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['tensorflow'], 'reason' => 'Machine learning framework', 'priority' => 220],
        ['label' => 'PyTorch', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['pytorch'], 'reason' => 'Machine learning framework', 'priority' => 220],
        ['label' => 'OpenCV', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['opencv'], 'reason' => 'Computer vision tooling', 'priority' => 220],
        ['label' => 'Wireshark', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['wireshark'], 'reason' => 'Network analysis tooling', 'priority' => 220],
        ['label' => 'Burp Suite', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['burp suite', 'burpsuite'], 'reason' => 'Security testing tooling', 'priority' => 220],
        ['label' => 'Nmap', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['nmap'], 'reason' => 'Security testing tooling', 'priority' => 220],
        ['label' => 'Metasploit', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['metasploit'], 'reason' => 'Security testing tooling', 'priority' => 220],
        ['label' => 'VMware', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['vmware'], 'reason' => 'Virtualization tooling', 'priority' => 220],
        ['label' => 'VirtualBox', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['virtualbox'], 'reason' => 'Virtualization tooling', 'priority' => 220],
        ['label' => 'Docker', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['docker'], 'reason' => 'Development tooling', 'priority' => 220],
        ['label' => 'Kubernetes', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['kubernetes', 'kubectl'], 'reason' => 'Infrastructure tooling', 'priority' => 220],
        ['label' => 'AWS', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'aws.amazon.com', 'keywords' => ['aws', 'lightsail', 'console.aws.amazon.com'], 'reason' => 'Cloud infrastructure', 'priority' => 220],
        ['label' => 'Azure', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'azure.microsoft.com', 'keywords' => ['azure'], 'reason' => 'Cloud infrastructure', 'priority' => 220],
        ['label' => 'Google Cloud', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'cloud.google.com', 'keywords' => ['google cloud', 'gcp'], 'reason' => 'Cloud infrastructure', 'priority' => 220],
        ['label' => 'Databricks', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'databricks.com', 'keywords' => ['databricks'], 'reason' => 'Data platform', 'priority' => 220],
        ['label' => 'Snowflake', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'snowflake.com', 'keywords' => ['snowflake'], 'reason' => 'Data platform', 'priority' => 220],
        ['label' => 'Splunk', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'splunk.com', 'keywords' => ['splunk'], 'reason' => 'Observability and security tooling', 'priority' => 220],
        ['label' => 'CrowdStrike', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'crowdstrike.com', 'keywords' => ['crowdstrike'], 'reason' => 'Security tooling', 'priority' => 220],
        ['label' => 'Jenkins', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'jenkins.io', 'keywords' => ['jenkins'], 'reason' => 'CI/CD tooling', 'priority' => 220],
        ['label' => 'CircleCI', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'circleci.com', 'keywords' => ['circleci'], 'reason' => 'CI/CD tooling', 'priority' => 220],
        ['label' => 'TravisCI', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'travis-ci.com', 'keywords' => ['travisci', 'travis ci'], 'reason' => 'CI/CD tooling', 'priority' => 220],
        ['label' => 'SonarQube', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'sonarqube.org', 'keywords' => ['sonarqube'], 'reason' => 'Code quality tooling', 'priority' => 220],
        ['label' => 'Snyk', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'snyk.io', 'keywords' => ['snyk'], 'reason' => 'Security tooling', 'priority' => 220],
        ['label' => 'Auth0', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'auth0.com', 'keywords' => ['auth0'], 'reason' => 'Identity platform', 'priority' => 220],
        ['label' => 'Okta', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'okta.com', 'keywords' => ['okta'], 'reason' => 'Identity platform', 'priority' => 220],
        ['label' => 'PingIdentity', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'pingidentity.com', 'keywords' => ['pingidentity'], 'reason' => 'Identity platform', 'priority' => 220],
        ['label' => 'Kaggle', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'kaggle.com', 'keywords' => ['kaggle'], 'reason' => 'Learning and data science practice', 'priority' => 210],
        ['label' => 'Hugging Face', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'huggingface.co', 'keywords' => ['hugging face', 'huggingface'], 'reason' => 'AI tooling and model research', 'priority' => 210],
        ['label' => 'HackTheBox', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'hackthebox.com', 'keywords' => ['hackthebox', 'hack the box'], 'reason' => 'Security practice', 'priority' => 210],
        ['label' => 'TryHackMe', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'tryhackme.com', 'keywords' => ['tryhackme', 'try hack me'], 'reason' => 'Security practice', 'priority' => 210],
        ['label' => 'Coursera', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'coursera.org', 'keywords' => ['coursera'], 'reason' => 'Learning platform', 'priority' => 210],
        ['label' => 'Udemy', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'udemy.com', 'keywords' => ['udemy'], 'reason' => 'Learning platform', 'priority' => 210],
        ['label' => 'Pluralsight', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'pluralsight.com', 'keywords' => ['pluralsight'], 'reason' => 'Learning platform', 'priority' => 210],
        ['label' => 'LeetCode', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'leetcode.com', 'keywords' => ['leetcode'], 'reason' => 'Engineering practice', 'priority' => 210],
        ['label' => 'HackerRank', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'hackerrank.com', 'keywords' => ['hackerrank'], 'reason' => 'Engineering practice', 'priority' => 210],
        ['label' => 'Grammarly', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'grammarly.com', 'keywords' => ['grammarly'], 'reason' => 'Writing assistance', 'priority' => 210],
        ['label' => 'Greenhouse', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'greenhouse.io', 'keywords' => ['greenhouse'], 'reason' => 'Hiring platform', 'priority' => 210],
        ['label' => 'Lever', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'lever.co', 'keywords' => ['lever'], 'reason' => 'Hiring platform', 'priority' => 210],
        ['label' => 'Lattice', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'lattice.com', 'keywords' => ['lattice'], 'reason' => 'People operations platform', 'priority' => 210],
        ['label' => 'Culture Amp', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'cultureamp.com', 'keywords' => ['culture amp', 'cultureamp'], 'reason' => 'People operations platform', 'priority' => 210],
        ['label' => 'Deel', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'deel.com', 'keywords' => ['deel'], 'reason' => 'Payroll and HR operations', 'priority' => 210],
        ['label' => 'Rippling', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'rippling.com', 'keywords' => ['rippling'], 'reason' => 'Payroll and HR operations', 'priority' => 210],
        ['label' => 'Sketch', 'tool_type' => 'software', 'classification' => 'productive', 'keywords' => ['sketch'], 'reason' => 'Design tooling', 'priority' => 210],
        ['label' => 'Zeplin', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'zeplin.io', 'keywords' => ['zeplin'], 'reason' => 'Design handoff tooling', 'priority' => 210],
        ['label' => 'Framer', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'framer.com', 'keywords' => ['framer'], 'reason' => 'Design tooling', 'priority' => 210],
        ['label' => 'Balsamiq', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'balsamiq.com', 'keywords' => ['balsamiq'], 'reason' => 'Wireframing tooling', 'priority' => 210],
        ['label' => 'Axure', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'axure.com', 'keywords' => ['axure'], 'reason' => 'Prototyping tooling', 'priority' => 210],
        ['label' => 'Scikit-learn', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'scikit-learn.org', 'keywords' => ['scikit-learn', 'sklearn'], 'reason' => 'Machine learning documentation', 'priority' => 210],
        ['label' => 'Seaborn', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'seaborn.pydata.org', 'keywords' => ['seaborn'], 'reason' => 'Data visualization tooling', 'priority' => 210],
        ['label' => 'Plotly', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'plotly.com', 'keywords' => ['plotly'], 'reason' => 'Data visualization tooling', 'priority' => 210],
        ['label' => 'SciPy', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'scipy.org', 'keywords' => ['scipy'], 'reason' => 'Scientific computing', 'priority' => 210],
        ['label' => 'Roboflow', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'roboflow.com', 'keywords' => ['roboflow'], 'reason' => 'Computer vision platform', 'priority' => 210],
        ['label' => 'Papers With Code', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'paperswithcode.com', 'keywords' => ['paperswithcode', 'papers with code'], 'reason' => 'Research reference', 'priority' => 210],
        ['label' => 'DataCamp', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'datacamp.com', 'keywords' => ['datacamp'], 'reason' => 'Learning platform', 'priority' => 210],
        ['label' => 'PortSwigger', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'portswigger.net', 'keywords' => ['portswigger'], 'reason' => 'Security tooling and training', 'priority' => 210],
        ['label' => 'Kali', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'kali.org', 'keywords' => ['kali.org', 'kali linux'], 'reason' => 'Security research', 'priority' => 210],
        ['label' => 'Offensive Security', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'offsec.com', 'keywords' => ['offensive security', 'offsec'], 'reason' => 'Security training', 'priority' => 210],
        ['label' => 'Celery', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'celeryq.dev', 'keywords' => ['celery'], 'reason' => 'Engineering documentation', 'priority' => 210],
        ['label' => 'SQLAlchemy', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'sqlalchemy.org', 'keywords' => ['sqlalchemy'], 'reason' => 'Engineering documentation', 'priority' => 210],
        ['label' => 'Vercel', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'vercel.com', 'keywords' => ['vercel'], 'reason' => 'Deployment platform', 'priority' => 210],
        ['label' => 'Netlify', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'netlify.com', 'keywords' => ['netlify'], 'reason' => 'Deployment platform', 'priority' => 210],
        ['label' => 'Heroku', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'heroku.com', 'keywords' => ['heroku'], 'reason' => 'Deployment platform', 'priority' => 210],
        ['label' => 'DigitalOcean', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'digitalocean.com', 'keywords' => ['digitalocean', 'digital ocean'], 'reason' => 'Infrastructure platform', 'priority' => 210],
        ['label' => 'SAP SuccessFactors', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'successfactors.com', 'keywords' => ['sap successfactors', 'successfactors'], 'reason' => 'HR platform', 'priority' => 210],
        ['label' => 'Paycom', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'paycom.com', 'keywords' => ['paycom'], 'reason' => 'Payroll platform', 'priority' => 210],
        ['label' => 'Paylocity', 'tool_type' => 'website', 'classification' => 'productive', 'domain' => 'paylocity.com', 'keywords' => ['paylocity'], 'reason' => 'Payroll platform', 'priority' => 210],
        ['label' => 'Crunchyroll', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'crunchyroll.com', 'keywords' => ['crunchyroll'], 'reason' => 'Entertainment streaming', 'priority' => 220],
        ['label' => 'Funimation', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'funimation.com', 'keywords' => ['funimation'], 'reason' => 'Entertainment streaming', 'priority' => 220],
        ['label' => 'Miniclip', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'miniclip.com', 'keywords' => ['miniclip'], 'reason' => 'Gaming and entertainment', 'priority' => 220],
        ['label' => 'Poki', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'poki.com', 'keywords' => ['poki'], 'reason' => 'Gaming and entertainment', 'priority' => 220],
        ['label' => 'IGN', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'ign.com', 'keywords' => ['ign'], 'reason' => 'Gaming and entertainment', 'priority' => 220],
        ['label' => 'GameSpot', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'gamespot.com', 'keywords' => ['gamespot'], 'reason' => 'Gaming and entertainment', 'priority' => 220],
        ['label' => 'Riot Games', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'riotgames.com', 'keywords' => ['riot games', 'riotgames'], 'reason' => 'Gaming and entertainment', 'priority' => 220],
        ['label' => 'StockX', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'stockx.com', 'keywords' => ['stockx'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'GOAT', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'goat.com', 'keywords' => ['goat'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'Nike', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'nike.com', 'keywords' => ['nike', 'snkrs', 'flight club'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'Adidas', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'adidas.com', 'keywords' => ['adidas'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'Puma', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'puma.com', 'keywords' => ['puma'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'Zara', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'zara.com', 'keywords' => ['zara'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'H&M', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'hm.com', 'keywords' => ['h&m', 'hm.com'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'Fragrantica', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'fragrantica.com', 'keywords' => ['fragrantica', 'parfumo'], 'reason' => 'Lifestyle browsing', 'priority' => 220],
        ['label' => 'Sephora', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'sephora.com', 'keywords' => ['sephora'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'BeReal', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'bere.al', 'keywords' => ['bereal', 'be real'], 'reason' => 'Social media entertainment', 'priority' => 220],
        ['label' => 'Shaadi', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'shaadi.com', 'keywords' => ['shaadi'], 'reason' => 'Personal browsing', 'priority' => 220],
        ['label' => 'BharatMatrimony', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'bharatmatrimony.com', 'keywords' => ['bharatmatrimony'], 'reason' => 'Personal browsing', 'priority' => 220],
        ['label' => 'Wattpad', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'wattpad.com', 'keywords' => ['wattpad'], 'reason' => 'Entertainment browsing', 'priority' => 220],
        ['label' => 'Patreon', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'patreon.com', 'keywords' => ['patreon'], 'reason' => 'Entertainment browsing', 'priority' => 220],
        ['label' => 'OnlyFans', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'onlyfans.com', 'keywords' => ['onlyfans'], 'reason' => 'Non-work browsing', 'priority' => 220],
        ['label' => 'Aaj Tak', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'aajtak.in', 'keywords' => ['aaj tak'], 'reason' => 'General news browsing', 'priority' => 220],
        ['label' => 'Republic TV', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'republicworld.com', 'keywords' => ['republic tv', 'republic world'], 'reason' => 'General news browsing', 'priority' => 220],
        ['label' => 'Zee News', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'zeenews.india.com', 'keywords' => ['zee news'], 'reason' => 'General news browsing', 'priority' => 220],
        ['label' => 'Grailed', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'grailed.com', 'keywords' => ['grailed'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'Farfetch', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'farfetch.com', 'keywords' => ['farfetch'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'SSENSE', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'ssense.com', 'keywords' => ['ssense'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'END Clothing', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'endclothing.com', 'keywords' => ['end clothing', 'end. clothing'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'Nordstrom', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'nordstrom.com', 'keywords' => ['nordstrom'], 'reason' => 'Shopping', 'priority' => 220],
        ['label' => 'MySpace', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'myspace.com', 'keywords' => ['myspace'], 'reason' => 'Social media entertainment', 'priority' => 220],
        ['label' => 'Tumblr', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'tumblr.com', 'keywords' => ['tumblr'], 'reason' => 'Social media entertainment', 'priority' => 220],
        ['label' => '9GAG', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => '9gag.com', 'keywords' => ['9gag'], 'reason' => 'Entertainment browsing', 'priority' => 220],
        ['label' => 'BuzzFeed', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'buzzfeed.com', 'keywords' => ['buzzfeed'], 'reason' => 'Entertainment browsing', 'priority' => 220],
        ['label' => 'Cricbuzz', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'cricbuzz.com', 'keywords' => ['cricbuzz'], 'reason' => 'Sports browsing', 'priority' => 220],
        ['label' => 'ESPN', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'espn.com', 'keywords' => ['espn'], 'reason' => 'Sports browsing', 'priority' => 220],
        ['label' => 'Hotstar', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'hotstar.com', 'keywords' => ['hotstar', 'disney+ hotstar'], 'reason' => 'Entertainment streaming', 'priority' => 220],
        ['label' => 'JioCinema', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'jiocinema.com', 'keywords' => ['jiocinema'], 'reason' => 'Entertainment streaming', 'priority' => 220],
        ['label' => 'Tinder', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'tinder.com', 'keywords' => ['tinder'], 'reason' => 'Personal browsing', 'priority' => 220],
        ['label' => 'Bumble', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'bumble.com', 'keywords' => ['bumble'], 'reason' => 'Personal browsing', 'priority' => 220],
        ['label' => 'Hinge', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'hinge.co', 'keywords' => ['hinge'], 'reason' => 'Personal browsing', 'priority' => 220],
        ['label' => 'OkCupid', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'okcupid.com', 'keywords' => ['okcupid'], 'reason' => 'Personal browsing', 'priority' => 220],
        ['label' => 'Match', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'match.com', 'keywords' => ['match.com'], 'reason' => 'Personal browsing', 'priority' => 220],
        ['label' => 'Roblox', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'roblox.com', 'keywords' => ['roblox'], 'reason' => 'Gaming and entertainment', 'priority' => 220],
        ['label' => 'Epic Games', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'epicgames.com', 'keywords' => ['epic games', 'epicgames'], 'reason' => 'Gaming and entertainment', 'priority' => 220],
        ['label' => 'Steam', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'steampowered.com', 'keywords' => ['steam'], 'reason' => 'Gaming and entertainment', 'priority' => 220],
        ['label' => 'Discord', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'discord.com', 'keywords' => ['discord'], 'reason' => 'Entertainment and community browsing', 'priority' => 220],
        ['label' => 'Twitch', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'twitch.tv', 'keywords' => ['twitch'], 'reason' => 'Entertainment streaming', 'priority' => 220],
        ['label' => 'Reddit', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'reddit.com', 'keywords' => ['reddit'], 'reason' => 'Entertainment and community browsing', 'priority' => 220],
        ['label' => '4chan', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => '4chan.org', 'keywords' => ['4chan'], 'reason' => 'Entertainment browsing', 'priority' => 220],
        ['label' => 'Rumble', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'rumble.com', 'keywords' => ['rumble'], 'reason' => 'Entertainment browsing', 'priority' => 220],
        ['label' => 'Vimeo', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'vimeo.com', 'keywords' => ['vimeo'], 'reason' => 'Video streaming', 'priority' => 220],
        ['label' => 'Dailymotion', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'dailymotion.com', 'keywords' => ['dailymotion'], 'reason' => 'Video streaming', 'priority' => 220],
        ['label' => 'Snapchat', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'snapchat.com', 'keywords' => ['snapchat'], 'reason' => 'Social media entertainment', 'priority' => 220],
        ['label' => 'TikTok', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'tiktok.com', 'keywords' => ['tiktok'], 'reason' => 'Social media entertainment', 'priority' => 220],
        ['label' => 'Instagram', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'instagram.com', 'keywords' => ['instagram', 'insta'], 'reason' => 'Social media entertainment', 'priority' => 220],
        ['label' => 'Facebook', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'facebook.com', 'keywords' => ['facebook'], 'reason' => 'Social media entertainment', 'priority' => 220],
        ['label' => 'Twitter X', 'tool_type' => 'website', 'classification' => 'unproductive', 'domain' => 'x.com', 'keywords' => ['x.com', 'twitter x'], 'reason' => 'Social media entertainment', 'priority' => 220],
        ['label' => 'Zerodha', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'zerodha.com', 'keywords' => ['zerodha'], 'reason' => 'Finance and market access', 'priority' => 200],
        ['label' => 'Upstox', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'upstox.com', 'keywords' => ['upstox'], 'reason' => 'Finance and market access', 'priority' => 200],
        ['label' => 'Groww', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'groww.in', 'keywords' => ['groww'], 'reason' => 'Finance and market access', 'priority' => 200],
        ['label' => 'AngelOne', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'angelone.in', 'keywords' => ['angelone', 'angel one'], 'reason' => 'Finance and market access', 'priority' => 200],
        ['label' => 'PolicyBazaar', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'policybazaar.com', 'keywords' => ['policybazaar'], 'reason' => 'Insurance and policy lookup', 'priority' => 200],
        ['label' => 'LIC India', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'licindia.in', 'keywords' => ['lic india', 'licindia'], 'reason' => 'Insurance and policy lookup', 'priority' => 200],
        ['label' => 'RedBus', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'redbus.in', 'keywords' => ['redbus'], 'reason' => 'Travel and commute planning', 'priority' => 200],
        ['label' => 'Yatra', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'yatra.com', 'keywords' => ['yatra'], 'reason' => 'Travel planning', 'priority' => 200],
        ['label' => 'Cleartrip', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'cleartrip.com', 'keywords' => ['cleartrip'], 'reason' => 'Travel planning', 'priority' => 200],
        ['label' => 'Speedtest', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'speedtest.net', 'keywords' => ['speedtest'], 'reason' => 'Network diagnostics', 'priority' => 200],
        ['label' => 'Dictionary', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'dictionary.com', 'keywords' => ['dictionary.com'], 'reason' => 'Reference lookup', 'priority' => 200],
        ['label' => 'Thesaurus', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'thesaurus.com', 'keywords' => ['thesaurus.com'], 'reason' => 'Reference lookup', 'priority' => 200],
        ['label' => 'Stack Exchange', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'stackexchange.com', 'keywords' => ['stack exchange', 'stackexchange'], 'reason' => 'General reference and Q&A', 'priority' => 200],
        ['label' => 'AccuWeather', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'accuweather.com', 'keywords' => ['accuweather'], 'reason' => 'Weather lookup', 'priority' => 200],
        ['label' => 'IMDb', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'imdb.com', 'keywords' => ['imdb'], 'reason' => 'Reference lookup', 'priority' => 200],
        ['label' => 'Goodreads', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'goodreads.com', 'keywords' => ['goodreads'], 'reason' => 'Reference lookup', 'priority' => 200],
        ['label' => 'Google Maps', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'maps.google.com', 'keywords' => ['google maps'], 'reason' => 'Travel and commute planning', 'priority' => 200],
        ['label' => 'Yahoo Mail', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'mail.yahoo.com', 'keywords' => ['yahoo mail'], 'reason' => 'Email and communication', 'priority' => 200],
        ['label' => 'Bing', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'bing.com', 'keywords' => ['bing'], 'reason' => 'Search and research', 'priority' => 200],
        ['label' => 'DuckDuckGo', 'tool_type' => 'website', 'classification' => 'neutral', 'domain' => 'duckduckgo.com', 'keywords' => ['duckduckgo', 'duck duck go'], 'reason' => 'Search and research', 'priority' => 200],
    ],
];
