{{--
  EVERY FORM CARRIES A PROVENANCE FOOTER. A statutory document that cannot say
  which system produced it, from which payroll period, and when, is one an
  inspector will not accept and an auditor cannot trace. It is also what stops
  a printed copy being mistaken for a signed original.
--}}
<table class="sign">
  <tr>
    <td class="line">Signature of employer or authorised signatory</td>
    <td></td>
    <td class="line">Date and place</td>
  </tr>
</table>

<div class="footer">
  Generated by {{ config('brand.product_label') }} on {{ optional($generatedAt ?? now())->format('d/m/Y H:i') }}@isset($run) · payroll period {{ $run->month_year ?? '—' }}@endisset ·
  This is a system-generated statement and is not valid without signature.
</div>

</body>
</html>
