<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Form 12BA — {{ $run->month_year ?? '' }}</title>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 10px; line-height: 1.45; color: #111; }
  h1 { font-size: 18px; margin: 0 0 4px; }
  h2 { font-size: 13px; margin: 14px 0 6px; border-bottom: 1px solid #333; padding-bottom: 3px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
  th, td { border: 1px solid #888; padding: 3px 5px; text-align: left; vertical-align: top; }
  th { background: #f3f3f3; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
  .header { text-align: center; margin-bottom: 12px; }
  .sub { font-size: 10px; color: #555; }
  .meta-grid { width: 100%; border: none; margin-bottom: 8px; }
  .meta-grid td { border: none; padding: 1px 4px; }
  .meta-grid td:first-child { width: 24%; font-weight: 600; }
  .footer { margin-top: 18px; font-size: 9px; color: #555; text-align: center; }
  .grand { font-weight: 700; background: #fffbe6; }
</style>
</head>
<body>

<div class="header">
  <h1>FORM 12BA</h1>
  <div class="sub">Statement of particulars of perquisites, other fringe benefits or amenities<br/>
    under section 17(2) of the Income-tax Act, 1961 (for the financial year)</div>
  <div class="sub"><strong>Period: {{ $run->month_year ?? '—' }}</strong></div>
</div>

<table class="meta-grid">
  <tr><td>Employer</td><td>{{ $employer->name ?? '—' }}</td></tr>
  <tr><td>TAN</td><td>{{ $tan ?: '—' }}</td></tr>
  <tr><td>PAN</td><td>{{ $pan ?: '—' }}</td></tr>
</table>

<table>
  <tr>
    <th>Employee</th>
    <th>PAN</th>
    <th class="num">Gross Salary (₹)</th>
    <th class="num">Perquisites (₹)</th>
    <th class="num">Profits in lieu (₹)</th>
    <th class="num">Total Income (₹)</th>
    <th class="num">TDS (₹)</th>
  </tr>
  @forelse($entries as $e)
  <tr>
    <td>{{ $e['employee'] }}</td>
    <td>{{ $e['pan'] ?: '—' }}</td>
    <td class="num">{{ number_format($e['gross_salary'], 2) }}</td>
    <td class="num">{{ number_format($e['perquisites'], 2) }}</td>
    <td class="num">{{ number_format($e['profits_in_lieu'], 2) }}</td>
    <td class="num">{{ number_format($e['total_income'], 2) }}</td>
    <td class="num">{{ number_format($e['tds'], 2) }}</td>
  </tr>
  @empty
  <tr><td colspan="7" class="num">No perquisite entries for this period.</td></tr>
  @endforelse
  <tr class="grand">
    <td><strong>Total</strong></td>
    <td></td>
    <td class="num"><strong>{{ number_format($totals['gross'], 2) }}</strong></td>
    <td class="num"><strong>{{ number_format($totals['perquisites'], 2) }}</strong></td>
    <td class="num"><strong>{{ number_format($totals['profits_in_lieu'], 2) }}</strong></td>
    <td class="num"><strong>{{ number_format($totals['total_income'], 2) }}</strong></td>
    <td class="num"><strong>{{ number_format($totals['tds'], 2) }}</strong></td>
  </tr>
</table>

<div class="footer">
  Generated by CareVance on {{ $generatedAt->format('d/m/Y') }}. Figures derived from payroll_items
  and active perquisite records for the period. To be issued to the employee alongside Form 16 Part B.
</div>

</body>
</html>
