import type { Metadata } from 'next';
import { ToolPage } from '@/components/tools/ToolPage';
import { PtStateTool } from '@/components/tools/PtStateTool';
import { PT_STATES, PT_LEVYING_COUNT, PT_NIL_COUNT } from '@/lib/pt-states';

export const metadata: Metadata = {
  title: 'Professional tax by state',
  description: `Professional tax slabs for all ${PT_STATES.length} Indian states and union territories, including the ${PT_NIL_COUNT} that levy none. Month-aware, with Maharashtra's higher February instalment modelled.`,
  alternates: { canonical: '/tools/professional-tax-by-state' },
};

const FAQS = [
  {
    q: 'Which states do not levy professional tax?',
    a: `${PT_NIL_COUNT} of the ${PT_STATES.length} states and union territories levy none — including Delhi, Haryana, Punjab, Rajasthan, Uttar Pradesh, Uttarakhand, Himachal Pradesh, Goa, Chandigarh and most of the smaller union territories. In those, the correct deduction is ₹0. A payroll system that defaults a missing state to a neighbour's slab is deducting a tax that does not exist.`,
  },
  {
    q: 'Why does Maharashtra charge more in February?',
    a: 'Professional tax is capped at ₹2,500 a year by Article 276(2) of the Constitution. Maharashtra’s top band is ₹200 a month, which reaches only ₹2,400 over twelve months, so February is charged at ₹300 to bring the annual total to ₹2,500. It applies to the top band only — charging it on a lower slab would overcharge someone the ceiling was never about.',
  },
  {
    q: 'Which state applies if my company and I are in different ones?',
    a: 'Generally the state where you actually work, because professional tax is levied on the exercise of a profession in that state. For remote employees this is the state you work from, not the state your employer is registered in — which is why a distributed team can need registrations in several states.',
  },
  {
    q: 'Is professional tax deductible from my income tax?',
    a: 'Yes. Professional tax paid is deductible from salary income under Section 16(iii) when computing taxable income — but under the old regime only. The new regime does not permit it.',
  },
  {
    q: 'Is there a maximum anyone can pay?',
    a: 'Yes — ₹2,500 a year, and it is a constitutional limit rather than a policy choice. Article 276(2) binds every state and union territory, so no state can levy more however it structures its slabs.',
  },
] as const;

export default function Page() {
  return (
    <ToolPage
      title="Professional tax by state"
      href="/tools/professional-tax-by-state"
      eyebrow="Free calculator"
      lede={`All ${PT_STATES.length} states and union territories — the ${PT_LEVYING_COUNT} that levy professional tax and the ${PT_NIL_COUNT} that do not. Month-aware, so February is right where it differs.`}
      calculator={<PtStateTool />}
      provenance="PTStateService::STATE_CONFIGS, read directly from the product and regenerated by a sync script rather than retyped. The February special rate and the top-band-only rule come from PTStateService::calculate."
      faqs={FAQS}
      related={[
        { href: '/tools/take-home-salary-calculator', label: 'Take-home salary' },
        { href: '/tools/salary-breakup-calculator', label: 'Salary breakup' },
      ]}
      explanation={
        <>
          <h2>A state tax, not a national one</h2>
          <p>
            Professional tax is levied by state governments on the exercise of a profession, trade
            or employment. There is no national rate and no national slab table, which is why a
            single “professional tax calculator” that asks only for your salary cannot be right.
          </p>
          <p>
            The consequence most often got wrong: <strong>{PT_NIL_COUNT} states and union
            territories levy nothing at all.</strong> Zero is a correct answer, not a missing one.
            A payroll system that quietly falls back to a default state when yours is unset is
            deducting a tax that does not exist and filing a return nobody asked for.
          </p>

          <h2>The ₹2,500 ceiling explains the odd numbers</h2>
          <p>
            Article 276(2) of the Constitution caps professional tax at ₹2,500 per person per year.
            Every strange-looking slab is a state working backwards from that limit — including
            Maharashtra’s ₹200 monthly charge with a ₹300 February, which lands exactly on ₹2,500
            over twelve months.
          </p>
          <p>
            The February rule applies to the top band only. Applying it across every slab is a
            common bug, and it overcharges lower earners who were never near the ceiling the rule
            exists to reach.
          </p>

          <h2>Why this table is generated, not typed</h2>
          <p>
            The slabs on this page are extracted directly from the CareVance payroll engine by a
            script, not transcribed by hand. Professional tax tables drift constantly, and a
            calculator that disagrees with the engine behind it would be worse than no calculator
            at all — so there is only one copy of these numbers, and this page reads it.
          </p>
        </>
      }
    />
  );
}
